### ISSUE TITLE
사용자 회원가입시 roles 등록 오류 발생

### ISSUE THREAD

**Issue by AyoungLim1103** [AyoungLim1103/spring-multi#21]
[오류 내용]
Request processing failed; nested exception is org.springframework.beans.InvalidPropertyException: Invalid property 'roles[0]' of bean class [net.joins.web.dto.MemberInfo]: Illegal attempt to get property 'roles' threw exception; nested exception is org.springframework.beans.NullValueInNestedPathException: Invalid property 'roles' of bean class [net.joins.web.dto.MemberInfo]: Could not instantiate property type [net.joins.web.dto.MemberRoleInfo] to auto-grow nested property path; nested exception is java.lang.NoSuchMethodException: net.joins.web.dto.MemberRoleInfo.<init>()
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014) ~[spring-webmvc-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) ~[spring-webmvc-5.2.8.RELEASE.jar:5.2.8.RELEASE]

사용자 roles 등록시 문제가 있는거 같습니다...

>>  main 브랜치까지 업로드 완료

**Comment by misolab** [comment]
@AyoungLim1103 변경이력을 보니깐 MemberInfo의 roles가 `MemberRole`에서 `MemberRoleInfo`로 변경되었더군요
오류 로그 젤 아래를 보면 `Caused by: java.lang.NoSuchMethodException: net.joins.web.dto.MemberRoleInfo.<init>()`라고 나오는데
MemberRoleInfo 에는 생성자가 없습니다.

그래서  아래처럼 생성자 코드를 넣으면 기존처럼 MemberInfo에 바인딩 되어 들어오게 됩니다.
```
@NoArgsConstructor
@AllArgsConstructor
public class MemberRoleInfo {
```
하지만 MemberMapper.INSTANCE.memberInfoToMember 에서 타입변환후 저장할때 오류가 나게되니 참고하세요
